from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('epaper', src, depend = ['USING_EPAPER'], CPPPATH = CPPPATH)

Return('group')
